### ISSUE TITLE
CE 1.9.2.3 Zend 1.12.16

### ISSUE THREAD

**Issue by ddoddsr** [EliasKotlyar/MagentoPHP56#1]
Thanks for writing this. Helping me upgrade to php 5.6 

Does  Magento 1.9.2.3 which includes the Zend framework version 1.12.16  handles this better now?

**Comment by EliasKotlyar** [comment]
As far as i see,they are still using the function iconv_get_encoding with the first parameter set to 'internal_encoding'. This plugin changes it to "default_charset". I assume that you still need this Extension,even on the recent Zend Framework 1.12.1.

**Comment by ddoddsr** [comment]
OK, will this still throw the notice on PHP 5.6 or higher then?
from lic/Zend/Locale/Format.php   line 1336
````
if (PHP_VERSION_ID < 50600) {
    iconv_set_encoding('internal_encoding', $encoding);
} else {
    ini_set('default_charset', $encoding);
}
````

**Comment by EliasKotlyar** [comment]
I suppose the bundled Framework will throw it. Just give it a try and apply this patch if its throwing warnings
